guidance-guarantee-programme/location-register

- Gemfile
- Gemfile.lock
- app/views/errors/bad_request.html.erb
- app/views/errors/forbidden.html.erb
- app/views/errors/internal_server_error.html.erb
- app/views/errors/method_not_allowed.html.erb
- app/views/errors/not_acceptable.html.erb
- app/views/errors/not_found.html.erb
- app/views/errors/not_implemented.html.erb
- app/views/errors/unauthorized.html.erb
- app/views/errors/unprocessable_entity.html.erb
- app/views/layouts/error.html.erb
- config/initializers/gaffe.rb
Similarly to [register_your_interest db75fbcab8](guidance-guarantee-programme/register_your_interest@db75fbc) by @andrewgarner
> Use gaffe for error messages

- app/controllers/admin/locations_controller.rb
- app/models/location.rb
- app/services/csv_generator.rb
- app/services/locations_csv.rb
- app/views/admin/locations/_directory_filter.html.erb
- config/initializers/csv_renderer.rb
- features/admin_locations_directory.feature
- features/pages/admin_location_directory_page.rb
- features/step_definitions/admin/location_directory_steps.rb
- spec/services/locations_csv_spec.rb
Allow locations to be exported in CSV format.
> Export locations to CSV

- app/controllers/admin/locations_controller.rb
- app/forms/locations_directory.rb
- app/views/admin/locations/_directory_filter.html.erb
- spec/forms/locations_directory_spec.rb
This extracts boolean flag issues out of the 
controller. This was required due to CSV filtering
not correctly set 'false' to false.
> Extract LocationsDirectory form object

- features/step_definitions/admin/edited_locations_steps.rb
- features/step_definitions/admin/location_directory_steps.rb
- features/step_definitions/admin/location_steps.rb
- features/support/factory_girl.rb
- spec/factories/location.rb
- spec/forms/locations_directory_spec.rb
- spec/models/address_spec.rb
- spec/models/edited_location_field_spec.rb
- spec/models/edited_location_spec.rb
- spec/models/location_spec.rb
- spec/policies/location_policy_spec.rb
- spec/rails_helper.rb
- spec/services/locations_csv_spec.rb
- spec/services/update_location_spec.rb
- spec/views/locations/index.html.jbuilder_spec.rb
i.e. use create(*) instead of FactoryGirl.create(*)
in tests
> Use FactoryGirl helper methods

- app/controllers/api/v1/booking_locations_controller.rb
- app/models/guider.rb
- app/models/location.rb
- app/models/slot.rb
- app/views/api/v1/booking_locations/_booking_location.json.jbuilder
- app/views/api/v1/booking_locations/show.json.jbuilder
- config/routes.rb
- db/migrate/20160610135053_create_guiders.rb
- db/schema.rb
- spec/factories/guiders.rb
- spec/factories/location.rb
- spec/features/booking_locations_api_spec.rb
- spec/models/location_spec.rb
- spec/models/slot_spec.rb
- spec/rails_helper.rb
- spec/views/api/v1/booking_locations/show.json.jbuilder_spec.rb
Adds a booking locations API endpoint to facilitate the centralised bookings client functionality.
Details are in the individual commits.
`GET /api/v1/booking_locations/:uid`
```
{
"uid": "9d7c72fc-0c74-4418-8099-e1a4e704cb01",
"name": "Romford CAB",
"address": "3 Some Road, Place, Romford, Essex, RM107BD",
"locations": [
// nested locations when present
],
"guiders": [
{
"id": 1,
"name": "Ben Lovell",
"email": "benjamin.lovell@gmail.com"
}
],
"slots": [
{
"date": "2016-06-13",
"start": "0900",
"end": "1300"
},
{
"date": "2016-06-13",
"start": "1300",
"end": "1700"
}
// further slots truncated
]
}
```
> Booking Locations API

- app/controllers/admin/locations_controller.rb
- app/models/location.rb
- app/policies/location_policy.rb
- app/services/create_or_update_location.rb
- app/views/admin/locations/_form.html.erb
- app/views/admin/locations/edit.html.erb
- app/views/admin/locations/new.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20160517154102_add_twilio_number_to_location.rb
- features/admin_location.feature
- features/admin_locations_create.feature
- features/cassettes/Create_a_new_location/Creating_a_location.yml
- features/cassettes/Create_a_new_location/Creating_a_location_as_a_pensionwise_admin.yml
- features/cassettes/Create_a_new_location/Creating_a_location_as_a_project_manager.yml
- features/pages/admin_new_location_page.rb
- features/step_definitions/admin/create_location_steps.rb
- features/step_definitions/admin/edited_locations_steps.rb
- features/step_definitions/admin/location_directory_steps.rb
- spec/factories/location.rb
- spec/services/update_location_spec.rb
- allow phone number to be set on creation only
- allow admin to set twilo number
- only allow location to become visible once twilo number is set
__NOTE:__
This change still required twilio redirects to be managed within the switchboard application as well as the location register.
> Allow creation of Location

- db/migrate/20160728144324_fix_guider_location_foreign_key.rb
- db/schema.rb
This was unnecessary and is broken anyway.
> Remove broken foreign key

- app/views/locations/index.json.jbuilder
- spec/views/locations/index.json.jbuilder_spec.rb
This will be used by `pension_guidance` and remove
the dependancy on the `switchboard` application
> Add Twilio number to /locations.json

- app/controllers/api/v1/twilio_numbers_controller.rb
- app/models/location.rb
- app/models/twilio_redirection.rb
- app/views/api/v1/twilio_numbers/index.json.jbuilder
- config/routes.rb
- spec/models/location_spec.rb
- spec/views/api/v1/twilio_numbers/index.json.jbuilder_spec.rb
Map Twilio numbers to deliver partner, location and
booking location for reporting.
> Add `/api/v1/twilo_numbers` endpoint

- .overcommit.yml
Ensure whitespace check and Rubocop run before commit
> Add overcommit to project

- app/controllers/admin/guiders_controller.rb
> Ensure we're dealing with an `active` location

- Gemfile
- app.json
- app/controllers/twilios_controller.rb
- app/models/twilio_redirection.rb
- app/models/twilio_redirection/call_centre.rb
- app/models/twilio_redirection/location.rb
- app/views/twilios/handle_status.xml.builder
- app/views/twilios/show.xml.builder
- config/initializers/filter_parameter_logging.rb
- config/routes.rb
- spec/controllers/twilios_controller_spec.rb
- spec/features/twilio_number_lookup_spec.rb
This code has been tested and is ready for deployment.
> Perform action for busy, no-answer and failed calls

- app/helpers/application_helper.rb
- app/views/layouts/admin/application.html.erb
Locations should be filtered based on the users
organisation (DP) as is done elsewhere in the application
> Filter locations returned in the location search

- .travis.yml
> Use heroku pipelines for deployment

- db/migrate/20170426115504_remove_booking_restrictions.rb
- db/schema.rb
Restores another phase of previously restricted locations:
Aberystwyth
Ammanford
Ammanford
Barnard Castle
Bishop Auckland
Brent
Brighton
Cambridge
Cardigan
Cardigan
Carmarthen
Chester-le-Street
Clapham Junction
Consett
Corwen
Darlington
Deeside
Denbigh
Droylsden
Durham
Ealing
Eastbourne
Ely
Enfield
Fareham
Fishguard
Guisborough
Hackney
Haringey
Harrow
Hartlepool
Haverfordwest
Huntingdon
Lewes
Llandrindod Wells (Jobcentre Plus)
Llandudno
Llanelli
Llanelli
Llanrumney
Middlesbrough
Mold
Neath
Newham
Newton Aycliffe
Newtown
Peterborough
Peterlee
Petersfield
Portsmouth
Rhyl
Seaford
Seaham
Spennymoor
St Leonards-on-Sea
Stockton & District
Swansea
Swinton
Tower Hamlets
Uckfield
Welshpool (Jobcentre Plus)
Westminster
Wisbech
> Active restricted locations for booking

- db/migrate/20170502122543_assign_further_plymouth_closures.rb
- db/schema.rb
They're still overwhelmed with outstanding appointments.
> Extend closure for Plymouth's locations

- app/controllers/admin/locations_controller.rb
This was causing issues when attempting to download varying CSVs.
> Don't cache CSV responses

- app/models/location.rb
This aids the switch away from twilio.
> Don't check for duplicate twilio numbers

- Gemfile.lock
- app/controllers/api/v1/booking_locations_controller.rb
- app/models/location.rb
- app/views/api/v1/booking_locations/index.json.jbuilder
- config/routes.rb
- spec/factories/location.rb
- spec/features/booking_locations_api_spec.rb
This lists all the currently active and online enabled locations.
> Add locations index to the API

- app/views/api/v1/booking_locations/_booking_location.json.jbuilder
- spec/views/api/v1/booking_locations/show.json.jbuilder_spec.rb
This will be used for a lookup in planner.
> Return `organisation` attribute in JSON

- app/views/api/v1/booking_locations/show.json.jbuilder
- spec/views/api/v1/booking_locations/show.json.jbuilder_spec.rb
This will be necessary for postcode searches in planner.
> Include geo point in booking locations API

- app/models/location.rb
- features/admin_location.feature
This is not necessary now so we can remove this restriction.
> Remove the validation for `hidden`
