guidance-guarantee-programme/location-register

spec/models/user_spec.rb

Lints the `User` model to ensure compatibility with the `GDS::SSO::User`
module. This insulates us against changes to the GDS-SSO API.

Ensure GDS-SSO / User compatibility

---

app/models/user.rb
app/policies/location_policy.rb
spec/factories/user.rb
spec/models/user_spec.rb
spec/policies/location_policy_spec.rb

- based off 'pensionwise_admin' in permissions
- This allow users to see/edit locations across 
organisations and is designed to be used by 
pension wise staff only.

Add pensionwise_admin access

---

app/controllers/admin/locations_controller.rb
app/services/update_location.rb
features/locations_admin_directory.feature
features/step_definitions/location_directory_steps.rb
spec/servcies/update_location_spec.rb

avoid database request to get object and allow
direct retrieval of uid value from object.

Ensure that editing a document creates a new version

---

db/migrate/20160405090141_add_active_record_lookups_to_replace_curie.rb
db/schema.rb

Please note that we are using `booking_location_uid` instead of `booking_location_id`
This is so we can get the latest details of the booking location.

Add active record id fields.

---

app/assets/stylesheets/admin/application.scss
app/assets/stylesheets/admin/components/_error-summary.scss
app/assets/stylesheets/admin/components/_form-group.scss
app/assets/stylesheets/admin/lib/_variables.scss
app/controllers/admin/locations_controller.rb
app/helpers/application_helper.rb
app/models/address.rb
app/models/location.rb
app/services/update_location.rb
app/views/admin/locations/_error.html.erb
app/views/admin/locations/_form.html.erb
config/locales/en.yml
features/admin_location.feature
features/pages/admin_edit_location_page.rb
features/step_definitions/admin/edited_locations_steps.rb
features/step_definitions/admin/location_steps.rb
spec/models/address_spec.rb
spec/services/update_location_spec.rb

Previously a failure during the editing process resulted the user being sent back to the index screen and an alert being displayed. 
This did not lend itself to understanding or correcting the error, it also didn't allow the user to review the values they had entered.
This update will re-render the edit page, with error messages, similar to the summary_generator.

Display errors within the form when editing

---

app/controllers/locations_controller.rb
spec/controllers/locations_controller_spec.rb

Add a flag to allow hidden locations to be included
in locations.json. This is required to get all locations
for the data platform.
Note: This is specifically to ensure we get Caerphilly
in the feed which is a hidden location as it does 
not have appointments, it is a call centre only.

Allow hidden locations to be returned in locations.json

---

app/controllers/admin/edited_locations_controller.rb
app/controllers/admin/locations_controller.rb
app/controllers/locations_controller.rb
app/models/location.rb
spec/controllers/locations_controller_spec.rb
spec/models/location_spec.rb

This corrects a bug that allowed hidden booking locations to appear in the edit drop down.
It also implemented the suggestion from @benlovell regarding moving logic from the controller to the model when it can to chained scopes and where conditions

Exclude hidden locations from booking locations

---

features/support/matchers.rb

The RSpec API changed a while back and this has been causing noise in
the spec and cukes output.

Remove `failure_message_for_should` warnings

---

Gemfile
Gemfile.lock
db/migrate/20160405145153_add_users_to_locations.rb

Since we use preloaded dynos we should actively highlight destructive schema
changes. Loading the `deprecated_columns` gem will warn for migrations with
persisted attributes not marked with the `deprecated_columns` macro.
Running the migrations from scratch caused issues with undefined model classes,
particularly `User` being an anachronism. I've simply wrapped the non-DDL parts
of the offending migration in a `defined?` check.

Warn on destructive migrations

---

Gemfile.lock

This breaks the ruby install with the latest bundler
version 1.12.5 in the new heroku-ruby-buildpack

Remove bundler/ruby version from Gemfile.lock

---

app/controllers/twilios_controller.rb
app/decorators/address_field_decorator.rb
app/decorators/booking_location_field_decorator.rb
app/decorators/visibility_field_decorator.rb
app/forms/locations_directory.rb
app/models/address.rb
app/models/call_centre.rb
app/models/location.rb
app/models/twilio_redirection.rb
app/validators/uk_phone_number_validator.rb
app/views/twilios/show.xml.builder
config/routes.rb
db/migrate/20160405090141_add_active_record_lookups_to_replace_curie.rb
spec/factories/call_center.rb
spec/features/twilio_number_lookup_spec.rb

[DO NOT MERGE] The first two commits needs to be merged and deployed separately to ensure
the system does not crash
Add Twilio phone number to location model and call center model to hold
promotional phone numbers.
Add Twilio XML endpoint.
This is a stage 1 to turning off the switchboard application.  Additional work still required:
* putting the Twilio number in /location.json 
* remove the switchboard dependancy from the pensionwise application
* testing the twilio redirections using the new endpoint
* other integration items.

Replace switchboard application

---

app/controllers/twilios_controller.rb

Without this set it raised an ActionController::InvalidAuthenticityToken
error. This should be removed if/when we move
to using get requests.

Allow post requests to /twilio without auth token

---

spec/spec_helper.rb

Nobody acts on this information so it's just noise in the spec output.

Remove spec profile reporting

---

README.md

Signon *is* implemented, plus we bumped Ruby to 2.3.1 a while back.

Update README in respect of Ruby and Signon

---

app/views/api/v1/booking_locations/_booking_location.json.jbuilder
db/migrate/20160707140820_add_online_booking_twilio_number_to_location.rb
db/schema.rb
spec/factories/location.rb
spec/views/api/v1/booking_locations/show.json.jbuilder_spec.rb

Adds the online booking specific twilio number to serialized locations
for the booking locations API. This is so we can track any online
booking specific interactions from customers.

Serialize online booking twilio number

---

app/models/location.rb
app/views/api/v1/booking_locations/_booking_location.json.jbuilder
spec/models/location_spec.rb

We were not respecting these flags so the response was
non-deterministic, given it included old and outdated versions of
locations.

Only return active and current locations

---

app/models/location.rb
app/views/admin/locations/_form.html.erb
config/locales/en.yml
db/migrate/20160809103637_remove_phone_when_booking_location.rb
db/schema.rb
features/admin_location.feature
features/pages/admin_edit_location_page.rb
features/step_definitions/admin/location_directory_steps.rb
features/step_definitions/admin/location_steps.rb
spec/factories/address.rb
spec/factories/location.rb
spec/models/address_spec.rb
spec/views/locations/index.json.jbuilder_spec.rb

When a booking location exists these fields should
be delegated to the booking location. this is required
to ensure that changes to these values on the 
booking location are propagated through.

Enforce blank phone/hours when booking location exists

---

app/models/location.rb
app/policies/location_policy.rb
app/views/admin/locations/_form.html.erb
config/locales/en.yml
spec/models/location_spec.rb
spec/policies/location_policy_spec.rb

Requires a corresponding Twilio number change
to occur.
This is to allow the new request from NICAB to change the external phone number of a booking location.

Allow phone numbers be edited by admin

---

app/models/location.rb
spec/models/location_spec.rb

This will allow phone numbers to be changed by 
pension wise admin without the need to make a 
corresponding twilio number change.

Remove phone validation (require twilio # change)

---

app/models/location.rb
app/models/twilio_redirection.rb
spec/factories/address.rb
spec/models/address_spec.rb
spec/models/twilio_redirect_spec.rb
spec/views/locations/index.json.jbuilder_spec.rb

When a twill number is updated, the old number
should continue to work and redirect to the
current phone number for the location.

Ensure old twilio number is redirected correctly

---

app/models/slot.rb
spec/models/slot_spec.rb
spec/views/api/v1/booking_locations/show.json.jbuilder_spec.rb

In keeping with some location's requirements around the earliest
available slots to book, the grace period for the earliest booking is
now mapped as follows:
```
Monday    | same Thursday
Tuesday   | same Friday
Wednesday | next Monday
Thursday  | next Tuesday
Friday    | next Wednesday
Saturday  | next Thursday
Sunday    | next Thursday
```

Increase grace period to three days (or more)

---

Gemfile
Gemfile.lock
app/controllers/admin/guiders_controller.rb
app/controllers/admin/locations_controller.rb
app/models/location.rb
app/policies/location_policy.rb
app/views/admin/guiders/index.html.erb
app/views/admin/locations/_form.html.erb
app/views/admin/locations/online_booking.html.erb
config/routes.rb
db/migrate/20161012092907_change_locations_online_booking_twilio_number_null.rb
db/schema.rb
features/admin_location.feature
features/pages/admin_edit_location_page.rb
features/pages/admin_guider_page.rb
features/step_definitions/admin/location_steps.rb
spec/policies/location_policy_spec.rb

_Note: This is very basic stuff just to speed up our process for enabling online booking locations. This will be incrementally improved as / when we have further locations to introduce._
Provides the location IDs heirarchically (including the booking location's
children) for us to copy-pasta or potentially curl for when enabling online
booking locations.
Adds a very simple guider administration screen. It isn't linked off the UI
anywhere as it is only used by us when adding guiders for online booking
enabled locations.
There is currently no validation or ability to edit / delete guiders. Maybe
I'll add that later should the need arise.
Grants administrators the ability to enter the online booking specific
twilio number on new or existing locations.
The number is now nullable, this is …

Additions for online bookings

---

app/views/api/v1/twilio_numbers/index.json.jbuilder
spec/views/api/v1/twilio_numbers/index.json.jbuilder_spec.rb

This is due to require for reporting to display
opening hours data beside call time information.
This will help to determine the number of unanswered
calls during opening hours for each location.

Add hours to /api/twilio_numbers endpoint

---

app/models/location.rb
app/views/api/v1/twilio_numbers/index.json.jbuilder
spec/models/location_spec.rb
spec/views/api/v1/twilio_numbers/index.json.jbuilder_spec.rb

This allow online booking number to be correctly
mapped in the reporting system.

Add online booking number to /api/twilio endpoint

---

app/models/location.rb
app/policies/location_policy.rb
app/views/admin/locations/_form.html.erb
app/views/admin/locations/_labels.html.erb
app/views/admin/locations/_location.html.erb
app/views/admin/locations/index.html.erb
app/views/admin/locations/show.html.erb
app/views/locations/index.json.jbuilder
config/locales/en.yml
db/migrate/20161025151439_add_online_enabled_to_location.rb
db/schema.rb
spec/factories/location.rb
spec/policies/location_policy_spec.rb
spec/views/locations/index.json.jbuilder_spec.rb

Allow online booking to be enabled/disabled for booking locations via the GUI.
This setting is then used in https://github.com/guidance-guarantee-programme/pension_guidance to enable/disable the online booking functionality.
Addition clean up of the interface to flag which locations are enabled and surface contact number has also been done.

Online booking

---

app/services/create_or_update_location.rb
spec/services/update_location_spec.rb

Previously editing a location would result in all
the guiders associated with it being left associated
with the old version of the location.

Ensure guiders are copied to new location on edit

---

app/models/location.rb
app/models/slot.rb
app/views/locations/index.json.jbuilder
config/initializers/holidays.rb
spec/models/slot_spec.rb

CAB office will be closed between 23 Dec and 2 Jan.
This is a quick fix to block these days out of the calendar.

Disallow booking requests for CAB holidays

---

Gemfile
Gemfile.lock
app/assets/javascripts/admin/application.js
app/assets/javascripts/admin/search.js
app/assets/stylesheets/admin/application.scss
app/assets/stylesheets/admin/components/_location.scss
app/assets/stylesheets/admin/lib/_variables.scss
app/helpers/application_helper.rb
app/models/location.rb
app/views/admin/locations/_location.html.erb
app/views/admin/locations/show.html.erb
app/views/layouts/admin/application.html.erb
features/admin_location.feature
features/step_definitions/admin/create_location_steps.rb

Use select2 to allow quick search and jump to
a location. In addition colour icons have been
to identify a location visibility.
Green open eye for active locations
Red closed eye for hidden locations
I'm not 100% sure on the green but it's the one currently in our palette:

Allow admin to search locations

---

app/models/postcode_geocoder.rb
features/admin_location.feature
features/cassettes/Admin_-_Location_Directory/Editing_a_locations_address_creates_a_new_version_with_the_updated_values/_set_postcode_LA6_2BG_.yml
spec/models/postcode_geocoder_spec.rb

Filter results returned from postcode geocoding
to only care when type is ['postal_code'].
This fixes the only occurance of this bug for
'LG6 2BG'. This process will still fail if multiple
results are returned which have a type of
['postal_code'].

Handle multiple results from geocoder lookup

---

app/models/postcode_geocoder.rb
spec/models/postcode_geocoder_spec.rb

This isn't entirely fool proof but rather than stating these are invalid
and not permitting the user to proceed, we can just accept the first set of
coordinates and move along. In practice the actual gaps between coordinates
are so trivially small that picking the first is usually the right thing to
do.

Permit first coordinates if there are multiple

---

app/models/location.rb
app/views/admin/locations/_labels.html.erb
app/views/locations/index.json.jbuilder
config/initializers/holidays.rb
db/migrate/20170216111618_correct_child_booking_enabled.rb
db/schema.rb

Online bookings for locations was previously controlled by the booking
location or parent location being enabled for online bookings. This
change allows us to specify that the booking location itself is enabled
for booking, but also whether individual children are enabled.
This change required a migration to blanket apply the
`online_booking_enabled` flag to existing child locations with booking
locations also enabled for online bookings already since previously the
flag was inferred from the parent as previously stated.

Allow children to opt out of online booking

---

app/models/location.rb
app/models/slot.rb
app/views/api/v1/booking_locations/_booking_location.json.jbuilder
app/views/api/v1/booking_locations/show.json.jbuilder
config/initializers/holidays.rb
db/migrate/20170228100601_add_cut_off_from_to_locations.rb
db/migrate/20170228103213_set_location_slot_cut_off_dates.rb
db/schema.rb
spec/models/location_spec.rb
spec/models/slot_spec.rb
spec/views/api/v1/booking_locations/show.json.jbuilder_spec.rb

Best reviewed commit-by-commit.
When the `cut_off_from` date stamp is present on a particular location, the
location will filter its slots to ensure none are present after the given
cut off.
Before merging:

[WIP] Allow locations to filter slots by cut-off date

---

db/migrate/20170303133843_additional_location_cut_offs.rb
db/schema.rb

Ensure no slots are returned from April 1 for these locations:
- Risca
- Cowbridge
- Ely & Caerau
- Llanrumney
- Maesteg
- Porthcawl
- Cardigan
- Ammanford
- Lampeter
- Llanelli
- Abergele
- Bala
- Corwen
- Deeside
- Mold
- Ruthin
- Berkhamsted
- Fishguard
- Milford Haven
- Narberth
- St Clears
- Dolgellau
- Neath
- Welshpool (Jobcentre Plus)
- Ystradgynlais (Jobcentre Plus)
- Chippenham
- Devizes
- Dursley
- Midsomer Norton
- Pwllheli

Mark further locations for closure

---

app/models/location.rb
spec/models/location_spec.rb

Adding a presence requirement that applies when online booking is enabled and there is no parent location.
`allow_blank` added to the format check so as not to have it return an invalid error in addition to failing the presence check.
Don't hugely like the repeated calls to `location.valid?` in the specs, but decided  to target the specific field's errors (rather than trying to also be able to call `be_valid`) to mitigate all the other validation going, so had sequence of events issues when it came to managing assignment of test values.

Add validation on the online booking twilio number

---

app/models/location.rb
app/views/api/v1/booking_locations/_booking_location.json.jbuilder
spec/models/location_spec.rb
spec/views/api/v1/booking_locations/show.json.jbuilder_spec.rb

We need to include hidden locations in the booking location API response to
insulate against changes being made to the size and structure of booking
locations and their respective child locations.
This isn't such an issue when used from the frontend's perspective but
causes lots of issues when planner refers to locations that no longer
'exist' in the API-sense.

Include hidden / inactive locations in response

---

db/migrate/20170309145932_correct_hidden_current_locations.rb
db/schema.rb

Alterations to the booking locations API mean we now include hidden
locations by default to maintain data integrity during the upcoming
moves. We noticed ~190 records that were incorrectly marked both
'current' and 'hidden' meaning they were returned and
displayed in planner and elsewhere that relies on this particular API.
This change ensures these locations will not be returned in the booking
locations API.

Correct current and hidden records

---

app/models/guider.rb
app/models/guider_assignment.rb
app/models/location.rb
db/migrate/20170314101829_create_guider_assignments.rb
db/schema.rb

We're converting the `guiders` association from `has_many` to
`has_many through:` to allow us to assign guiders to multiple
locations. This is to support the reassignment of child locations to
booking locations.
When a child moves to a new parent it needs to bring with it the
associated guiders for the parent location to maintain data integrity
via the booking locations API.
This processed is stepped as we are migrating from a typical
`belongs_to` to a join table approach and this cannot be migrated in a
single atomic step.

Begin conversion of `guiders` association

---

app/controllers/admin/guiders_controller.rb
app/models/guider.rb
app/models/location.rb
app/services/create_or_update_location.rb
db/migrate/20170315105142_remove_location_id_from_guiders.rb
db/schema.rb
spec/factories/guiders.rb
spec/factories/location.rb
spec/services/update_location_spec.rb

This was supplementary to 8c71e20 and completes the changes required for
guiders to exist in multiple locations.

Allow guiders to belong to multiple locations

---

app/models/location.rb
app/views/locations/index.json.jbuilder
config/initializers/holidays.rb
spec/factories/location.rb
spec/features/bank_holiday_spec.rb

Largely just duplicating the previous implementation in 1e7e233612ee833a71b0dd6bc8804cf6879518b5.
Extra date for the May Day bank holiday added following discussion in this morning's standup.

Disable online booking for upcoming bank holidays

---

app/services/create_or_update_location.rb
spec/services/update_location_spec.rb

Previously we only triggered this behaviour in response to a child
location being reassigned to a new booking location. This change
ensures booking locations can also be reassigned.

Notify dependent systems when reassigning

---

db/migrate/20170324102734_further_location_cut_offs.rb
db/schema.rb

The following locations are to be marked for closure:
Aberystwyth
Ammanford
Barnard Castle
Bermondsey
Bexleyheath
Bishop Auckland
Bognor Regis
Brecon
Brecon (Jobcentre Plus)
Brent
Brentford & Chiswick
Brighton
Cambridge
Cardigan
Carmarthen
Chester-le-Street
Chichester
Clapham Junction
Consett
Dalston
Darlington
Denbigh
Durham
Ealing
Eastbourne
Ely
Enfield
Fareham
Guisborough
Hackney
Hammersmith and Fulham
Haringey
Harrow
Hartlepool
Havant
Haverfordwest
Hillingdon
Holywell
Horsham
Huntingdon
Lampeter
Lancing
Lewes
Lewisham
Littlehampton
Llandrindod Wells
Llandrindod Wells (Jobcentre Plus)
Llandudno
Llanelli
Llangollen
Llanwrst
Machynlleth (Jobcentre Plus)
Middlesbrough
Mitcham
Morden
Newham
Newton Aycliffe
Newtown
Peckham
Pembroke Dock
Peterborough
Peterlee
Petersfield
Portsmouth
Rhyl …

Mark these locations for closure on 2017/04/21

---

app/views/locators/index.html.erb

I don't see any reason why we have 'Enniskillen' as the default location in the search box

Remove default location in search box

---

app/models/slot.rb
config/initializers/holidays.rb
spec/models/slot_spec.rb

This ensures folks cannot book appointments for bank holidays when
locations are closed.
Also includes all bank holidays throughout 2017.

Ensure slots for bank holidays are skipped

---

app/models/location.rb

This is stopping us from moving locations around heirarchically when
the current (booking) location is being reassigned to a new parent
booking location.

Don't validate `phone` absence so strictly

---

app/views/admin/locations/index.html.erb

To make it easier to access the location edit page this restores the location name as a link
Minor adjustment to the position of the edit button

Link Location name in the Location Directory

---

config/initializers/govuk_admin_template.rb

We weren't differentiating the environments as we do with our other
applications. This can cause confusion - especially with staging and
production.

Display environment labels and highlighting

---

app/assets/javascripts/locator/google-maps-and-markers.js

This ensures the child location's number is used instead of the booking
location's number when a value is provided.

Use child location's number when provided

---

app/models/location.rb
app/policies/location_policy.rb
app/services/create_or_update_location.rb
app/views/admin/locations/_form.html.erb
app/views/api/v1/booking_locations/_booking_location.json.jbuilder
db/migrate/20170413090950_add_booking_reply_to_email_to_locations.rb
db/schema.rb
spec/factories/location.rb
spec/policies/location_policy_spec.rb
spec/views/api/v1/booking_locations/show.json.jbuilder_spec.rb

This permits admins to supply an online booking specific reply-to address.
They can supply a previously configured group mailbox alias and this will
be set for any online booking related emails via the planner application
when present in the booking locations API.

Allow admins to supply an booking reply-to email

---

app/models/location.rb
app/models/slot.rb
db/migrate/20170420121609_add_cut_off_to_to_locations.rb
db/migrate/20170420123641_assign_cut_off_to_for_plymouth_locations.rb
db/schema.rb
spec/models/location_spec.rb

When we specify a `cut_off_to` date, slots will not be available for
bookings until after that date. Unlike `cut_off_from` - a hard closure of a
location - this still keeps the location open and available to take
bookings but introduces a 'breathing' period to ease processing a backlog
of bookings.

Introduce a temporary cut-off period

---

app/controllers/admin/locations_controller.rb
app/models/location.rb
spec/models/location_spec.rb

* don't assert lack of guiders when a child location
* stop swallowing validation errors on the location edit page

Updates to location validation

---

app/models/location.rb
spec/features/bank_holiday_spec.rb

Before this change we hid the online booking button. We now allow
customers to enter the bookings process regardless whether the current
day is a public holiday. This makes sense as the slots and cut-off
period logic will not allow a customer to book an appointment *for* a
public holiday, yet nothing ought to stop a customer from placing a
booking during this period.

Allow bookings during bank holidays

---

app/models/location.rb
spec/models/location_spec.rb

Unfortunately it seems booking location IDs are updated to empty strings
now, not `nil` as they were before. This means the logic to determine
whether a location is a booking location was slightly off. We ought to
accomodate both `nil` and empty strings when performing this check.

Correct booking location query

---

app/assets/javascripts/locator/google-maps-and-markers.js

Since some child locations are now taking bookings via their own direct phone number, if they have one populated we display it on the marker it in the same way that we would if it were a booking location.
**A booking location**
**A child location**
**A child location with their own number**

Update manner in which we render information for map markers

---

app/models/twilio_redirection.rb
app/models/twilio_redirection/location.rb
spec/features/twilio_number_lookup_spec.rb
spec/models/twilio_redirect_spec.rb

A requested change in the redirection behaviour.
Currently when a call comes in to a location's Twilio number and that location has a booking location, we redirect the call to that booking location's number.
The amended behaviour now checks the location for a number of its own and if present uses that over that of the booking location.

If present redirect to a location’s phone number over that of the booking location

---

app/services/locations_csv.rb
spec/services/locations_csv_spec.rb

Adds the parent organisation to the exported CSV so we can easily
report and filter upon organisation membership.

Include `organisation` when exporting CSV

---

app/models/location.rb
app/views/api/v1/booking_locations/_booking_location.json.jbuilder
spec/models/location_spec.rb
spec/views/api/v1/booking_locations/show.json.jbuilder_spec.rb

Introduces logic to resolve a canonical online booking twilio number.
When the child's number is present this is used to override the
parent's.

Return the canonical online booking number

---

db/migrate/20171006095026_correct_call_centre_numbers.rb
db/schema.rb

We're now handing off calls made to these locations to the call centre
so bookings can be placed without handoffs.

Direct CITA/NICAB calls to call centre

---

.env.development
.travis.yml
README.md
app/helpers/google_maps_api_helper.rb
app/views/locators/index.html.erb
spec/helpers/google_maps_api_helper_spec.rb

This is a fix in response to a P3 raised by Abdul.
-----
Description: We have noticed that the locator maps here is showing a 'for development purposes' error. This interface is also used by TP agent so slightly concerned that it may affect their role. There's a small chance it might be because the google maps account may not have been paid. However, the issue may be unrelated and the colleagues familiar with the payment systems are currently not at work
Steps taken: This seems to happen regardless of browser / user.
Action required: Investigate potential issue with locator maps

Google maps api key

---

app/models/location.rb
app/policies/location_policy.rb
app/views/admin/locations/_form.html.erb
app/views/api/v1/booking_locations/_booking_location.json.jbuilder
app/views/locations/index.json.jbuilder
db/migrate/20181031101324_add_realtime_to_locations.rb
db/schema.rb
spec/factories/location.rb
spec/policies/location_policy_spec.rb
spec/views/api/v1/booking_locations/show.json.jbuilder_spec.rb
spec/views/locations/index.json.jbuilder_spec.rb

Adds a flag that persists through the various location APIs to signify
the specific location is realtime enabled.

Allow locations to be realtime enabled

---

app/models/edited_location.rb

This wasn't configured before so audits for changes to the realtime
booking status of a location were not tracked.

Audit changes to `realtime`

---

app/controllers/admin/guiders_controller.rb
app/helpers/guiders_helper.rb
app/models/guider.rb
app/views/admin/guiders/index.html.erb
config/routes.rb
features/admin_location.feature
features/pages/admin_guider_page.rb
features/step_definitions/admin/location_steps.rb

This isn't idle but it was the pattern that proliferated across the
platform. Once we have all locations enrolled in the realtime we can
come back and tidy up how guider visibility works.

Allow guider visibility to be toggled

---

Gemfile
Gemfile.lock
app/services/create_or_update_location.rb
features/admin_location.feature
features/pages/admin_location_page.rb
features/step_definitions/admin/location_steps.rb
features/support/javascript_driver.rb
spec/models/location_spec.rb

Locations without an organisation assigned from creation cannot 
subsequently be assigned an organisation. This was due to an issue with the
dodgy versioning scheme bailing out of a transaction and swallowing the
error.

Ensure organisations can be assigned

---

app/models/user.rb
app/policies/location_policy.rb
spec/factories/location.rb
spec/factories/user.rb
spec/policies/location_policy_spec.rb

This allows them to see locations for CITA E & W and NI when they're assigned the `project_manager` permission.

Scope locations for CITA E & W project managers

---

app/policies/location_policy.rb
spec/policies/location_policy_spec.rb

This was an issue caused by the recent change to scoped access for CITA E&W users. The necessary changes were not included to cover individual access permissions.

Ensure permission scopes are correct

---

app/policies/location_policy.rb
app/views/admin/locations/edit.html.erb
spec/policies/location_policy_spec.rb

Allows the project managers to change telephone numbers and guiders in their organisation tree.

Expand project manager permissions

---

app/policies/location_policy.rb
app/views/admin/locations/_form.html.erb
features/step_definitions/admin/create_location_steps.rb
spec/policies/location_policy_spec.rb

The organisations were not being set correctly so the project managers were not able to create locations for their organisational divisions.

Ensure locations can be managed correctly by CITA

---

app/models/guider.rb

This was causing issues downstream in planner when someone was adding and assigning a guider with a blank name.

Ensure guider names are present
